### ISSUE TITLE
how to manage history trends using same repo for smoke testing and performance testing and both are creating separate reports and separate workflows 

### ISSUE THREAD

**Issue by ashokvaddevalli** [ashikkumar23/github-action-with-allure-report#12]

**Comment by ashikkumar23** [comment]
@ashokvaddevalli 

# Managing Allure History Trends for Multiple Workflows in the Same Repo

When running **smoke testing** and **performance testing** in the same repository, each with separate reports and workflows, it’s important to ensure their Allure history trends are maintained independently. Here’s how to set it up properly:

---

## How Allure History Works

- **Allure trends** are based on persisting and supplying the previous report’s `/history` directory to the next workflow run.
- Each test type (smoke, performance) should have its own `history` folder and report to keep trends clean and isolated.

---

## Recommended Approach

### 1. Separate Report Paths

- Use distinctive paths for report results:
  - Smoke: `allure-results-smoke/`
  - Performance: `allure-results-performance/`

### 2. Distinct Artifacts and History Files

- For each workflow, upload and download a unique artifact for history:
    - Smoke: `allure-history-smoke`
    - Performance: `allure-history-performance`
- Always download the corresponding history before generating a new report, and upload the updated history after.

### 3. Example Workflow Steps

<details>
<summary>Sample GitHub Actions steps for Smoke Testing</summary>

```yaml
- name: Download Allure History
  uses: actions/download-artifact@v3
  with:
    name: allure-history-smoke
    path: ./allure-results-smoke/history

- name: Generate Allure Report
  run: allure generate ./allure-results-smoke -o ./allure-report-smoke --clean

- name: Upload Allure History
  uses: actions/upload-artifact@v3
  with:
    name: allure-history-smoke
    path: ./allure-report-smoke/history
```
</details>

<details>
<summary>Sample GitHub Actions steps for Performance Testing</summary>

```yaml
- name: Download Allure History
  uses: actions/download-artifact@v3
  with:
    name: allure-history-performance
    path: ./allure-results-performance/history

- name: Generate Allure Report
  run: allure generate ./allure-results-performance -o ./allure-report-performance --clean

- name: Upload Allure History
  uses: actions/upload-artifact@v3
  with:
    name: allure-history-performance
    path: ./allure-report-performance/history
```
</details>

### 4. Keep Workflows and Publishing Separate

- Use distinct workflow `.yml` files for each test type.
- Publish or host reports in different locations (e.g., separate GitHub Pages, S3 buckets, folders, etc.).

### 5. Never Share History Artifacts Across Test Types

- Smoke and performance tests **must never** share the same Allure `history` artifact.
- This ensures accurate and meaningful trend data for each test type.

---

## **Summary**

- **Isolate** report paths and history per workflow.
- **Use unique artifact names** for each test type.
- **Handle `/history` directories and steps separately** in their respective workflows.
- This will produce accurate, clean trend tracking for both smoke and performance testing in one repository.

---
